
CREATE TABLE TBLBOARD(
	IDX				INT				NOT NULL,
	MEMID			VARCHAR(20)		NOT NULL,
	TITLE			VARCHAR(100)	NOT NULL,
	CONTENT 		VARCHAR(2000)	NOT NULL,
	WRITER			VARCHAR(30)		NOT NULL,
	INDATE			DATETIME DEFAULT NOW(),
	COUNT 			INT DEFAULT 0,
	-- 댓글 기능 추가 --
	BOARDGROUP		INT, -- 부모 댓글 하나의 그룹 -- 
	BOARDSEQUENCE	INT, -- 같은 그룹 안에서 댓글의 순서 --
	BOARDLEVEL		INT, -- 1단계 댓글인지 2단계 댓글인지에 대한 정보 --
	BOARDAVAILABLE	INT, -- 삭제된 글인지에 대한 여부 --
	PRIMARY KEY(IDX)
);

INSERT INTO TBLBOARD
SELECT IFNULL(MAX(IDX)+1, 1), -- 만약 IDX가 존재하면 최댓값 + 1, 존재하지 않으면 1 --
'aischool', '공지사항입니다', '다음주 월요일 정상 등원하겠습니다.', '교육운영부',
NOW(), 0,
IFNULL(MAX(BOARDGROUP)+1, 1), 0, 0, 1
FROM TBLBOARD;


INSERT INTO TBLBOARD
SELECT IFNULL(MAX(IDX)+1, 1), -- 만약 IDX가 존재하면 최댓값 + 1, 존재하지 않으면 1 --
'222222222', '2번글입니다', '2번글 내용입니다', '22222',
NOW(), 0,
IFNULL(MAX(BOARDGROUP)+1, 1), 0, 0, 1
FROM TBLBOARD;



INSERT INTO TBLBOARD
SELECT IFNULL(MAX(IDX)+1, 1), -- 만약 IDX가 존재하면 최댓값 + 1, 존재하지 않으면 1 --
'33333333', '3번글입니다', '3번글 내용입니다', '3333333333',
NOW(), 0,
IFNULL(MAX(BOARDGROUP)+1, 1), 0, 0, 1
FROM TBLBOARD;

SELECT * FROM TBLBOARD;





CREATE TABLE TBLMEMBER(
	MEMID		VARCHAR(50)		NOT NULL,
	MEMPWD		VARCHAR(50)		NOT NULL,
	MEMNAME		VARCHAR(50)		NOT NULL,
	MEMPHONE	VARCHAR(50)		NOT NULL,
	MEMADDR		VARCHAR(100),
	LATITUDE	DECIMAL(13, 10), -- 현재위치위도 --
	LONGITUDE	DECIMAL(13, 10), -- 현재위치경도 --
	PRIMARY KEY(MEMID)
);




INSERT INTO TBLMEMBER(MEMID, MEMPWD, MEMNAME, MEMPHONE)
VALUES('aischool', '1234', 'AIAIAI', '010-1234-1234');
INSERT INTO TBLMEMBER(MEMID, MEMPWD, MEMNAME, MEMPHONE)
VALUES('222222222', '1234', '2번의닉네임', '010-2222-2222');
INSERT INTO TBLMEMBER(MEMID, MEMPWD, MEMNAME, MEMPHONE)
VALUES('33333333', '1234', '3번의닉네임', '010-3333-3333');

SELECT * FROM TBLMEMBER;


