DROP TABLE AUTH;
DROP TABLE MEMBER;




SELECT * FROM MEMBER;

SELECT * FROM BOARD;

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('춥춥','가을','가으리');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('9시','12분','미닛');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('디비','디비디비','딥');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('뇽뇽','디뇽디뇽','다이노');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('두엘레','카베사','코라손');
